server:
  port: 7001
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: KakYE1XlN1GZBGz3yewo
    url: jdbc:mysql://raisehand-mysql.cfaycya26uuv.rds.cn-north-1.amazonaws.com.cn:3306/raise?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/xml/*.xml


